import type { LoopConfig } from './types';

export const PRESETS: Record<string, LoopConfig> = {
  'delivery-loop': {
    title: 'Delivery lifecycle',
    lobes: { left: 'Dev', right: 'Ops' },
    stages: [
      { name: 'Plan', label: 'Shape the work', note: 'Agree the problem\nSize the outcome\nPick a success measure' },
      { name: 'Code', label: 'Build it', note: 'Small changes\nReview before merge\nKeep it reversible' },
      { name: 'Build', label: 'Package', note: 'Reproducible builds\nPin dependencies\nScan for vulnerabilities' },
      { name: 'Test', label: 'Check it works', note: 'Automated suites\nCover the risky paths\nFail fast and loudly' },
      { name: 'Release', label: 'Approve', note: 'Change record raised\nSign-off captured\nRollback plan ready' },
      { name: 'Deploy', label: 'Ship safely', note: 'Progressive rollout\nGuardrails per environment\nOne switch to stop it' },
      { name: 'Operate', label: 'Run it', note: 'Watch the golden signals\nHandle incidents\nKeep costs in view' },
      { name: 'Monitor', label: 'Learn and feed back', arrow_depth: 96, note: 'Measure real usage\nCompare against the goal\nSend findings back to Plan' },
    ],
    style: {
      theme: 'dark',
      width: 2300,
      height: 1300,
      scale: 640,
      curve: 'rings',
      ring_ratio: 0.6,
      reverse: true,
      offset: 5.5,
      ribbon_width: 112,
      segment_style: 'arrow',
      arrow_depth: 46,
      badge_layout: 'quadrant',
      row_margin: 46,
      badge_radius: 38,
      badge_label_size: 27,
      note_size: 25,
      note_wrap: 30,
      note_bullet: '· ',
      label_size: 26,
      title_size: 40,
      loop_label_size: 62,
      loop_icon_stroke: 4,
      grid: true,
      grid_dash: '4,11',
    },
  },
  'n-plus-one': {
    title: 'The N+1 Bicycle Acquisition Lifecycle',
    lobes: { left: 'Rider', right: 'Excuses' },
    stages: [
      { name: 'Trails', label: 'Need a mountain bike', note: 'The trails are rough\nYour current bike is "too precious"\nThis is clearly a safety purchase' },
      { name: 'Gravel', label: 'Need a gravel bike', note: 'Road bike is too fragile\nMTB is too slow\nYou discover gravel YouTube' },
      { name: 'Tarmac', label: 'Need a road bike', note: 'The gravel bike weighs a ton\nSomeone mentions the club run\nMarginal gains are a lifestyle' },
      { name: 'Winter', label: 'Need a winter bike', note: 'Salt will eat the good one\nMudguards ruin the lines\nCheaper than a new drivetrain' },
      { name: 'Commute', label: 'Need a commuter', note: 'You will not lock up the good one\nPanniers do not fit a race bike\nIt pays for itself, allegedly' },
      { name: 'Tour', label: 'Need a touring bike', note: 'Nothing you own takes a rack\nTwo nights out needs a third cage\nSteel is comfortable, obviously' },
      { name: 'Track', label: 'Need a track bike', note: 'One gear builds character\nThe session is already booked\nBarely a bike, so it hardly counts' },
      { name: 'Storage', label: 'Need a bigger shed', arrow_depth: 88, note: 'The hallway is now a bike shop\nSomeone has views on the hallway\nA shed is not a bike, so N is unchanged' },
    ],
    style: {
      theme: 'dark',
      width: 1900,
      height: 1060,
      scale: 500,
      curve: 'rings',
      ring_ratio: 0.6,
      ribbon_width: 96,
      segment_style: 'arrow',
      arrow_depth: 40,
      badge_layout: 'quadrant',
      row_margin: 40,
      badge_radius: 34,
      badge_label_size: 22,
      note_size: 18,
      note_wrap: 28,
      note_bullet: '· ',
      label_size: 24,
      title_size: 34,
      loop_label_size: 46,
      grid: true,
      grid_dash: '4,11',
    },
  },
  'blank': {
    stages: [
      { name: 'Stage 1' },
      { name: 'Stage 2' },
      { name: 'Stage 3' },
      { name: 'Stage 4' },
    ],
    style: {
      theme: 'dark',
      curve: 'rings',
      ring_ratio: 0.7,
    },
  },
};
